# Generated by Django 3.1.4 on 2021-07-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodingSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('in_progress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hackerank_star', models.CharField(max_length=100)),
                ('project_complete', models.CharField(max_length=100)),
                ('project_ongoing', models.CharField(max_length=100)),
                ('internship', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DevelopmentSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('in_progress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_completion', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('about_course', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_completion', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('about_course', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mywork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('title', models.CharField(max_length=100)),
                ('catogary', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='pics')),
                ('post', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('current_city', models.CharField(max_length=100)),
                ('full_address', models.TextField()),
                ('age', models.IntegerField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_num', models.CharField(max_length=100)),
            ],
        ),
    ]
