# Generated by Django 3.1.4 on 2021-07-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfolio', '0005_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=1000)),
                ('instgram', models.CharField(max_length=1000)),
                ('github', models.CharField(max_length=1000)),
                ('linkedin', models.CharField(max_length=1000)),
                ('resume', models.CharField(max_length=1000)),
            ],
        ),
    ]
